"""
YouTube upload pipeline — automated video uploads with SEO metadata.
Uses YouTube Data API v3 with OAuth2 service account.
"""

import os
import httpx
from datetime import datetime
from config import get_settings


YOUTUBE_UPLOAD_URL = "https://www.googleapis.com/upload/youtube/v3/videos"
YOUTUBE_API_URL = "https://www.googleapis.com/youtube/v3"

CATEGORY_PLAYLIST_MAP = {
    "technology": "Technology & AI",
    "finance": "Finance & Markets",
    "politics": "Politics & World",
    "business": "Business",
    "health": "Health & Science",
    "sports": "Sports",
    "entertainment": "Entertainment",
    "geopolitics": "World News",
    "general": "General News",
    "science": "Science",
}


async def upload_video(
    video_path: str,
    title: str,
    description: str,
    category: str = "general",
    tags: list[str] | None = None,
    language: str = "en",
    thumbnail_path: str | None = None,
) -> dict:
    """
    Upload a video to YouTube with metadata.

    Args:
        video_path: Local path or URL to the video file
        title: Video title (max 100 chars)
        description: Video description
        category: News category for playlist assignment
        tags: SEO tags
        language: Content language code
        thumbnail_path: Optional custom thumbnail

    Returns:
        Dict with video_id, url, and status
    """
    settings = get_settings()
    access_token = getattr(settings, "youtube_access_token", "")

    if not access_token:
        return {"status": "skipped", "reason": "YouTube credentials not configured"}

    if tags is None:
        tags = ["ANN", "AI News", "Breaking News", category.title()]

    yt_description = (
        f"{description[:4500]}\n\n"
        f"---\n"
        f"Generated by A.N.N. — AI News Network\n"
        f"The world's first autonomous AI news network\n\n"
        f"#ANN #AINews #{category.title().replace(' ', '')} #BreakingNews\n\n"
        f"Subscribe for 24/7 AI-generated news broadcasts."
    )

    metadata = {
        "snippet": {
            "title": title[:100],
            "description": yt_description,
            "tags": tags[:30],
            "categoryId": "25",  # News & Politics
            "defaultLanguage": language,
            "defaultAudioLanguage": language,
        },
        "status": {
            "privacyStatus": "public",
            "selfDeclaredMadeForKids": False,
            "embeddable": True,
            "publicStatsViewable": True,
        },
    }

    try:
        async with httpx.AsyncClient(timeout=300.0) as client:
            # For URL-based videos, download first
            if video_path.startswith("http"):
                video_response = await client.get(video_path)
                video_data = video_response.content
            else:
                with open(video_path, "rb") as f:
                    video_data = f.read()

            # Resumable upload
            init_response = await client.post(
                f"{YOUTUBE_UPLOAD_URL}?uploadType=resumable&part=snippet,status",
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Content-Type": "application/json",
                    "X-Upload-Content-Type": "video/mp4",
                    "X-Upload-Content-Length": str(len(video_data)),
                },
                json=metadata,
            )

            if init_response.status_code != 200:
                return {"status": "failed", "error": init_response.text[:300]}

            upload_url = init_response.headers.get("location")
            if not upload_url:
                return {"status": "failed", "error": "No upload URL returned"}

            upload_response = await client.put(
                upload_url,
                content=video_data,
                headers={"Content-Type": "video/mp4"},
            )

            if upload_response.status_code == 200:
                data = upload_response.json()
                video_id = data.get("id", "")
                return {
                    "status": "uploaded",
                    "platform": "youtube",
                    "video_id": video_id,
                    "url": f"https://youtube.com/watch?v={video_id}",
                }
            else:
                return {"status": "failed", "error": upload_response.text[:300]}

    except Exception as e:
        return {"status": "error", "platform": "youtube", "error": str(e)}


async def set_thumbnail(video_id: str, thumbnail_path: str) -> dict:
    """Set a custom thumbnail for an uploaded video."""
    settings = get_settings()
    access_token = getattr(settings, "youtube_access_token", "")

    if not access_token:
        return {"status": "skipped"}

    try:
        if thumbnail_path.startswith("http"):
            async with httpx.AsyncClient() as client:
                r = await client.get(thumbnail_path)
                thumb_data = r.content
        else:
            with open(thumbnail_path, "rb") as f:
                thumb_data = f.read()

        async with httpx.AsyncClient(timeout=30.0) as client:
            r = await client.post(
                f"{YOUTUBE_API_URL}/thumbnails/set?videoId={video_id}",
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Content-Type": "image/png",
                },
                content=thumb_data,
            )
            return {"status": "set" if r.status_code == 200 else "failed"}

    except Exception as e:
        return {"status": "error", "error": str(e)}


async def add_to_playlist(video_id: str, playlist_id: str) -> dict:
    """Add an uploaded video to a category playlist."""
    settings = get_settings()
    access_token = getattr(settings, "youtube_access_token", "")

    if not access_token:
        return {"status": "skipped"}

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            r = await client.post(
                f"{YOUTUBE_API_URL}/playlistItems?part=snippet",
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Content-Type": "application/json",
                },
                json={
                    "snippet": {
                        "playlistId": playlist_id,
                        "resourceId": {"kind": "youtube#video", "videoId": video_id},
                    }
                },
            )
            return {"status": "added" if r.status_code == 200 else "failed"}

    except Exception as e:
        return {"status": "error", "error": str(e)}
