import { View, Text, ScrollView, Pressable } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { api } from "../../lib/api";

export default function ArticleScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [lang, setLang] = useState<"en" | "hi">("en");

  const { data: scripts } = useQuery({
    queryKey: ["scripts"],
    queryFn: () => api.scripts(50),
  });

  const script = (scripts || []).find((s: any) => s.id === id);

  if (!script) {
    return (
      <View style={{ flex: 1, backgroundColor: "#05050a", justifyContent: "center", alignItems: "center" }}>
        <Text style={{ color: "#64748b", fontSize: 14 }}>Article not found</Text>
      </View>
    );
  }

  const content = lang === "hi" ? script.hindi_script : script.english_script;

  return (
    <ScrollView style={{ flex: 1, backgroundColor: "#05050a" }} contentContainerStyle={{ padding: 16 }}>
      {/* Category + Meta */}
      <Text style={{ color: "#818cf8", fontSize: 10, fontWeight: "700", textTransform: "uppercase", letterSpacing: 1 }}>
        {script.category}
      </Text>

      <Text style={{ color: "#f8fafc", fontSize: 22, fontWeight: "bold", marginTop: 8, lineHeight: 28 }}>
        {script.headline}
      </Text>

      <View style={{ flexDirection: "row", gap: 12, marginTop: 10 }}>
        <Text style={{ color: "#475569", fontSize: 11 }}>{script.word_count_en} words</Text>
        <Text style={{ color: "#475569", fontSize: 11 }}>~{script.estimated_duration_seconds}s broadcast</Text>
        <Text style={{ color: "#475569", fontSize: 11 }}>5 languages</Text>
      </View>

      {/* Language Toggle */}
      <View style={{ flexDirection: "row", gap: 8, marginTop: 16 }}>
        <Pressable
          onPress={() => setLang("en")}
          style={{
            paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20,
            backgroundColor: lang === "en" ? "rgba(129,140,248,0.15)" : "rgba(255,255,255,0.05)",
          }}
        >
          <Text style={{ color: lang === "en" ? "#818cf8" : "#64748b", fontSize: 12, fontWeight: "600" }}>🇬🇧 English</Text>
        </Pressable>
        <Pressable
          onPress={() => setLang("hi")}
          style={{
            paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20,
            backgroundColor: lang === "hi" ? "rgba(129,140,248,0.15)" : "rgba(255,255,255,0.05)",
          }}
        >
          <Text style={{ color: lang === "hi" ? "#818cf8" : "#64748b", fontSize: 12, fontWeight: "600" }}>🇮🇳 हिन्दी</Text>
        </Pressable>
      </View>

      {/* Script Content */}
      <View style={{ marginTop: 20, padding: 16, backgroundColor: "rgba(255,255,255,0.02)", borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" }}>
        <Text style={{ color: "#cbd5e1", fontSize: 15, lineHeight: 24 }}>
          {content?.replace(/\[PAUSE\]/g, "\n\n— PAUSE —\n\n")}
        </Text>
      </View>

      {/* Footer */}
      <View style={{ marginTop: 20, alignItems: "center", paddingBottom: 40 }}>
        <Text style={{ color: "#334155", fontSize: 10 }}>Generated by A.N.N. — AI News Network</Text>
      </View>
    </ScrollView>
  );
}
