"""
A.N.N. RSS 2.0 Feed Generator
Generates standard RSS 2.0 XML feeds for news distribution.
Other websites and aggregators can subscribe to this feed.
"""

import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from xml.dom import minidom
from models.schemas import BroadcastScript


def generate_rss_feed(
    scripts: list[BroadcastScript],
    base_url: str = "http://localhost:8000",
    title: str = "A.N.N. — AI News Network",
    description: str = "AI-powered autonomous news broadcasts in English and Hindi",
    category: str | None = None,
    language: str = "en",
) -> str:
    # Register namespaces locally or module level to avoid duplicate xmlns settings
    ET.register_namespace("atom", "http://www.w3.org/2005/Atom")
    ET.register_namespace("media", "http://search.yahoo.com/mrss/")
    ET.register_namespace("dc", "http://purl.org/dc/elements/1.1/")
    ET.register_namespace("content", "http://purl.org/rss/1.0/modules/content/")

    rss = ET.Element("rss", version="2.0")

    channel = ET.SubElement(rss, "channel")

    feed_title = f"{title} — {category.title()}" if category else title
    ET.SubElement(channel, "title").text = feed_title
    ET.SubElement(channel, "link").text = f"{base_url}/news"
    ET.SubElement(channel, "description").text = description
    ET.SubElement(channel, "language").text = language
    ET.SubElement(channel, "generator").text = "A.N.N. AI News Network v1.0"
    ET.SubElement(channel, "lastBuildDate").text = _rfc822_now()
    ET.SubElement(channel, "ttl").text = "15"
    ET.SubElement(channel, "copyright").text = (
        f"© {datetime.now().year} A.N.N. AI News Network. Generated by AI."
    )

    atom_link = ET.SubElement(channel, "{http://www.w3.org/2005/Atom}link")
    feed_url = f"{base_url}/feed/rss"
    if category:
        feed_url += f"?category={category}"
    atom_link.set("href", feed_url)
    atom_link.set("rel", "self")
    atom_link.set("type", "application/rss+xml")

    image = ET.SubElement(channel, "image")
    ET.SubElement(image, "url").text = f"{base_url}/public/ann-logo.png"
    ET.SubElement(image, "title").text = title
    ET.SubElement(image, "link").text = f"{base_url}/news"

    for script in scripts:
        item = ET.SubElement(channel, "item")
        ET.SubElement(item, "title").text = script.headline
        ET.SubElement(item, "link").text = f"{base_url}/news#script-{script.id}"
        ET.SubElement(item, "guid", isPermaLink="false").text = f"ann-{script.id}"
        ET.SubElement(item, "pubDate").text = _rfc822(script.created_at)
        ET.SubElement(item, "category").text = script.category.value.title()
        ET.SubElement(item, "{http://purl.org/dc/elements/1.1/}creator").text = "A.N.N. AI News Network"

        excerpt = script.english_script.replace("[PAUSE]", "").strip()
        if len(excerpt) > 500:
            excerpt = excerpt[:500] + "..."
        ET.SubElement(item, "description").text = excerpt

        # ElementTree will natively html-escape this perfectly, feed-readers decode it easily.
        content = (
            f"<h2>{script.headline}</h2>\n"
            f"<p><strong>Category:</strong> {script.category.value.title()}</p>\n"
            f"<p><strong>Duration:</strong> ~{script.estimated_duration_seconds} seconds</p>\n"
            f"<hr/>\n"
            f"<h3>English Script</h3>\n"
            f"<p>{script.english_script.replace('[PAUSE]', '<em>[pause]</em>').replace(chr(10), '<br/>')}</p>\n"
            f"<hr/>\n"
            f"<h3>Hindi Script (हिन्दी)</h3>\n"
            f"<p>{script.hindi_script.replace('[PAUSE]', '<em>[pause]</em>').replace(chr(10), '<br/>')}</p>\n"
            f"<hr/>\n"
            f"<p><em>Generated by A.N.N. — AI News Network</em></p>\n"
        )

        content_encoded = ET.SubElement(item, "{http://purl.org/rss/1.0/modules/content/}encoded")
        content_encoded.text = content

    return _prettify(rss)

def _rfc822(dt: datetime) -> str:
    """Convert datetime to RFC 822 format for RSS."""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.strftime("%a, %d %b %Y %H:%M:%S %z")


def _rfc822_now() -> str:
    """Current time in RFC 822."""
    return _rfc822(datetime.now(timezone.utc))


def _escape_xml(text: str) -> str:
    """Escape XML special characters."""
    if not text:
        return ""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _prettify(element: ET.Element) -> str:
    """Pretty-print XML with proper declaration."""
    rough = ET.tostring(element, encoding="unicode", xml_declaration=False)
    with open("debug.xml", "w", encoding="utf-8") as f:
        f.write(rough)
    dom = minidom.parseString(rough)
    pretty = dom.toprettyxml(indent="  ", encoding=None)
    # Remove extra XML declaration from minidom and add our own
    lines = pretty.split("\n")
    if lines[0].startswith("<?xml"):
        lines[0] = '<?xml version="1.0" encoding="UTF-8"?>'
    return "\n".join(lines)
